# Generated by Django 5.2.6 on 2025-09-13 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_musicafavorita_delete_filme'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MusicaNaPlaylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_adicao', models.DateTimeField(auto_now_add=True)),
                ('musica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.musicafavorita')),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='musicas', to='app.playlist')),
            ],
            options={
                'unique_together': {('playlist', 'musica')},
            },
        ),
    ]
